name: bhukk1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_carousel_widget: ^2.2.0
  image_picker: ^1.1.2
  provider: ^6.1.4
  connectivity_plus: ^6.1.3
  lottie: ^2.6.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  font_awesome_flutter: ^10.8.0
  get: ^4.7.2
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ad1.jpg
    - assets/images/ad2.jpg
    - assets/images/ad3.jpg
    - assets/images/splash.png
    - assets/images/bhukk_logo.png
    - assets/images/partner.png
    - assets/icons/
    - assets/cafes/restaurant.jpg
    - assets/icons/food.png

  #fonts:
  #  - family: Poppins
   #   fonts:
   #     - asset: assets/fonts/Poppins-Regular.ttf
    #    - asset: assets/fonts/Poppins-Medium.ttf
    #      weight: 500
    #    - asset: assets/fonts/Poppins-SemiBold.ttf
    #      weight: 600
    #    - asset: assets/fonts/Poppins-Bold.ttf
    #      weight: 700
